[ERROR][Mon, 15 Nov 2021 10:30:00][kline_service.py][line:104]: data length is zero
